version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db

    ports:
      - "4000:27017"
    restart: always
  azure-storage:
    image: azure-storage
    build:
      context: ./azure_storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=STORAGE_ACCOUNT_NAME
      - STORAGE_ACCESS_KEY=STORAGE_ACCESS_KEY
    restart: "no"
  video_streaming:
    image: video_streaming 
    build:
      context: ./video_streaming
      dockerfile: Dockerfile
    container_name: video_streaming
    ports:
      - "4002:3000"
    environment: 
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
