version: '3'
services:

  video_streaming:
    image: video_streaming 
    build:
      context: ./video_streaming
      dockerfile: Dockerfile
    container_name: video_streaming
    ports:
      - "4000:80"
    environment: 
      - PORT=80
    restart: "no"